export const LETTUCE_ADD = 'LETTUCE_ADD'
export const LETTUCE_REMOVE = 'LETTUCE_REMOVE'
export const BACON_ADD = 'BACON_ADD'
export const BACON_REMOVE = 'BACON_REMOVE'
export const CHEESE_ADD = 'CHEESE_ADD'
export const CHEESE_REMOVE = 'CHEESE_REMOVE'
export const MEAT_ADD = 'MEAT_ADD'
export const MEAT_REMOVE = 'MEAT_REMOVE'